[package]
name = "auto_fishing"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = {version="0.13.1", features=["tokio"]}
rusty-tesseract = "=1.0.1"
smart-default = "0.7.1"
tokio = { version = "1.44.2", features = ["full"] }
tray-item = {version = "0.10.0", features= ["ksni"]}
